// @flow

const API_INITIALISE: string = 'API_INITIALISE'
const API_INITIALISE_SUCCESS: string = 'API_INITIALISE_SUCCESS'
const API_INITIALISE_FAILURE: string = 'API_INITIALISE_FAILURE'
const FETCH_COLUMN_STATISTICS: string = 'FETCH_COLUMN_STATISTICS'
const FETCH_COLUMN_STATISTICS_SUCCESS: string = 'FETCH_COLUMN_STATISTICS_SUCCESS'
const FETCH_COLUMN_STATISTICS_FAILURE: string = 'FETCH_COLUMN_STATISTICS_FAILURE'
const HIDE_NOTIFICATION: string = 'HIDE_NOTIFICATION'
const SHOW_NOTIFICATION: string = 'SHOW_NOTIFICATION'

export {
  API_INITIALISE,
  API_INITIALISE_SUCCESS,
  API_INITIALISE_FAILURE,
  FETCH_COLUMN_STATISTICS,
  FETCH_COLUMN_STATISTICS_SUCCESS,
  FETCH_COLUMN_STATISTICS_FAILURE,
  HIDE_NOTIFICATION,
  SHOW_NOTIFICATION
}
