// @flow

const API_INITIALISE: string = 'API_INITIALISE'
const API_INITIALISE_SUCCESS: string = 'API_INITIALISE_SUCCESS'
const API_INITIALISE_FAILURE: string = 'API_INITIALISE_FAILURE'

export {
  API_INITIALISE
}
